import { readFileSync, writeFileSync } from 'node:fs';
import { World, PRESETS, type Preset } from '../src/engine';
const report = JSON.parse(readFileSync('public/archive/pattern-hunt.json', 'utf8'));
function normalized(w: World) {
  const cells: number[][] = []; let x0 = w.n, y0 = w.n, xmax = 0, ymax = 0;
  for (let i = 0; i < w.a.length; i++) if (w.a[i] || w.c[i] || w.m[i]) {
    const x = i % w.n, y = Math.floor(i / w.n); x0 = Math.min(x0,x); y0 = Math.min(y0,y); xmax = Math.max(xmax,x); ymax = Math.max(ymax,y); cells.push([x,y,w.a[i],w.c[i],w.m[i]]);
  }
  return {key:JSON.stringify(cells.map(([x,y,...rest]) => [x-x0,y-y0,...rest])),x:x0,y:y0,interior:x0>1&&y0>1&&xmax<w.n-2&&ymax<w.n-2,cells:cells.length};
}
const unique = new Set(); const verified = [];
for(const candidate of report.movingCandidates) {
  const id = candidate.preset + ':' + candidate.trial; if(unique.has(id))continue;unique.add(id);
  const w = new World(128,PRESETS[candidate.preset as Preset]);
  for(const [x,y,a,c] of candidate.seed) { const i=(64+y)*128+64+x;w.a[i]=a;w.c[i]=c; }
  for(let t=0;t<candidate.from;t++)w.step();
  const origin=normalized(w);let valid=origin.interior;
  const period=candidate.to-candidate.from;
  for(let cycle=1;cycle<=8;cycle++) {
    for(let t=0;t<period;t++){w.step();if(!normalized(w).interior)valid=false;}
    const next=normalized(w);
    if(next.key!==origin.key||next.x-origin.x!==candidate.dx*cycle||next.y-origin.y!==candidate.dy*cycle)valid=false;
  }
  if(valid)verified.push({...candidate,period,grid:128,verifiedCycles:8,occupied:origin.cells});
}
report.verifiedTravelers=verified;
writeFileSync('public/archive/pattern-hunt.json',JSON.stringify(report,null,2)+'\n');
if (!verified.length) throw new Error('No traveler passed verification');
const chosen = {skater: verified.find(v => v.preset === 'loom' && v.dx === 1 && v.dy === -1), dart: verified.find(v => v.preset === 'comets' && v.occupied === 4)};
if (!chosen.skater || !chosen.dart) throw new Error('Expected travelers missing');
writeFileSync('src/traveler.ts','// Generated by scripts/travelers.ts; full-state translation verified over eight cycles.\nexport const TRAVELERS = '+JSON.stringify(chosen,null,2)+' as const;\n');
console.log(JSON.stringify(verified.map(({preset,period,dx,dy,occupied})=>({preset,period,dx,dy,occupied}))));
