export const notes = `
<div class="notes-heading"><p class="eyebrow">FIELD NOTES / 001</p><h1 id="notes-title">The six-cell spring.</h1><p>A small, reproducible surprise in a world we made up.</p><span class="note-meta">September 11, 2026 · Palimpsest v0.1</span></div>
<div class="notebook">
<article>
  <section><h2>Start with six cells.</h2><p>Two active A pulses. Four cells counting down through recovery. No B pulses, no stored memory, and no randomness after the start.</p><div class="seed-figure"><div class="seed-grid" aria-label="The six-cell seed: row one, recovery 3 and A; row two, recovery 4 and recovery 2; row three, recovery 3 and A"><span>3</span><span class="seed-a">A</span><span>4</span><span>2</span><span>3</span><span class="seed-a">A</span></div><p>Letters are active pulses.<br>Numbers are recovery timers.<br>Everything around them is empty.</p></div><p>At tick 6, the first B pulses appear. The seed becomes a source of expanding, alternating fronts. We call it the <strong>six-cell spring</strong>.</p><a class="inline-action" href="#lab">Plant the spring ↗</a></section>
  <section><h2>More memory can kill it.<br>Even more brings it back.</h2><p>Change only the amount of memory each pulse deposits. The same seed passes through four distinct outcomes:</p><div class="table-wrap"><table><thead><tr><th>Memory deposit</th><th>Eventual behavior</th></tr></thead><tbody><tr><td>0–5</td><td>A-only clock · period 6</td></tr><tr><td>6</td><td>A-only clock · period 7</td></tr><tr><td>7–19</td><td>Extinction · all state becomes zero</td></tr><tr><td>20–64</td><td>A/B clock · period 26</td></tr></tbody></table></div><p>Every integer setting from 0 to 64 was tested on a 48 × 48 grid with absorbing edges. The rule suggests a mechanism: intermediate memory inhibits A without supporting B strongly enough; stronger memory allows the opposite pulse to ignite.</p><p>These boundaries describe this seed and these rules. They are not a guarantee for arbitrary starting patterns.</p></section>
  <section><h2>A repeat we can verify.</h2><p>On a 96 × 96 grid, the complete state at tick 89 is identical to tick 63. That includes pulses, recovery timers, and ground memory—not just the pixels in a picture.</p><div class="cycle-line" aria-label="Tick 63 original state, tick 76 pulse types inverted, tick 89 original state repeats"><span><strong>63</strong>Original state</span><span><strong>76</strong>A ↔ B</span><span><strong>89</strong>Exact repeat</span></div><p>After 13 ticks, every pulse sign and memory sign is reversed, with recovery timers unchanged. After 26, everything returns. A deterministic world that reaches an identical state must repeat the same future.</p><div class="table-wrap"><table><thead><tr><th>Grid</th><th>Repeating from tick</th><th>Period</th></tr></thead><tbody><tr><td>48 × 48</td><td>39</td><td>26</td></tr><tr><td>96 × 96</td><td>63</td><td>26</td></tr><tr><td>192 × 192</td><td>111</td><td>26</td></tr></tbody></table></div><p>These are finite worlds with absorbing edges: nothing returns from the other side. The certificate establishes indefinite repetition on the tested finite grids; it does not prove an infinite-grid result.</p><a href="/archive/cycle-certificate.json">Read the cycle certificates ↓</a></section>
  <section><h2>The world’s rules.</h2><p>Each cell remembers three integers: its pulse (<code>−1, 0, +1</code>), a recovery timer, and a signed ground memory. Every cell updates at the same time.</p><ol><li>Count A and B pulses in the eight neighboring cells, as <code>P</code> and <code>N</code>.</li><li>Compute each pulse type’s support, including the old ground memory.</li><li>A resting cell with at least one active neighbor fires the winning type if its score reaches the threshold. Ties remain quiet.</li><li>An active cell becomes quiet and starts its recovery timer. Other timers count down toward zero.</li><li>Memory fades by one toward zero, then the old pulse adds its signed deposit.</li></ol><pre><code>bias    = truncate(memory / 2)
A score = 4P − 2N − bias
B score = 4N − 2P + bias

next memory = clamp(
  memory − sign(memory) + 24 × pulse,
  −64, +64
)</code></pre><p>The spring uses Cathedral: threshold 4, recovery 4 ticks, deposit 24, memory capacity 64, divisor 2, and a crowding limit of 8. Estuary and Tidal change these six parameters, keeping the same update mechanism.</p><p>The faint trails are actual ground memory, not decorative motion blur. A cell can switch pulse type when memory outweighs its neighbors’ influence.</p></section>
  <section><h2>What we searched. What survived.</h2><p>This began as a short exploration with a simple ambition: find a small invented world with something worth getting excited about.</p><ol><li><strong>144 initial settings.</strong> The first rule required an existing neighbor of the same pulse type. Some early winners lost one type on a larger grid.</li><li><strong>A revised rule; 240 settings.</strong> Memory was allowed to induce the opposite type. We tested 144 settings, then 96 more with a penalty for short repeats.</li><li><strong>Held-out worlds.</strong> Cathedral and Estuary were each tested on four new seeds at three sizes, with and without memory, for 2,400 ticks. Some Estuary worlds nearly died.</li><li><strong>480 small seeds.</strong> A search across three presets found this six-cell pattern, which maintained central activity and both pulse types.</li><li><strong>Attack the candidate.</strong> We tested its subsets, ran it for 6,000 ticks on three grid sizes, removed memory, and finally checked exact state recurrence.</li></ol><p>The search scores were practical heuristics, not validated measures of complexity. The six-cell seed is not proven globally minimal. All nonempty subsets of its six occupied sites were tested with their original timer values; only the complete pattern passed the chosen sustained-core criterion.</p></section>
  <section><h2>Reproduce it.</h2><p>The live site and verification tools share the same TypeScript engine. Tests compare it against saved Python fixtures for all three presets, and independently check the cycle, sign inversion, and deposit sweep.</p><pre><code>git clone git@github.com:junovhs/palimpsest.git
cd palimpsest
npm ci
npm test
npm run verify
npm run dev</code></pre><p>The verifier writes fresh certificates into <code>verification/</code>. It checks actual state arrays after using SHA-256 to locate a possible repeat. The original Python reference and search program remain in <code>reference/</code>.</p></section>
  <section><h2>Where this sits.</h2><p>Excitable cellular automata, oscillators, and memory feedback are established ideas. Palimpsest is a particular rule family and a documented experiment inside it. We have not established that this exact rule or seed is a world first.</p><p>What we do have is an inspectable object: the seed, its full rules, an unexpected transition, and checks anyone can run.</p><ul class="source-list"><li><a href="https://arxiv.org/abs/patt-sol/9304001">Fisch, Gravner & Griffeath — Threshold-Range Scaling of Excitable Cellular Automata</a></li><li><a href="https://arxiv.org/abs/1111.3525">Adamatzky & Chua — Phenomenology of retained refractoriness</a></li><li><a href="https://arxiv.org/abs/1212.2821">Alonso-Sanz & Adamatzky — On Memory and Structural Dynamism in Excitable Cellular Automata</a></li></ul></section>
</article>
<aside class="archive"><p class="eyebrow">OPEN NOTEBOOK</p><h2>Take a closer look.</h2><a href="/archive/spring-hunt.md">11 more spring sources <span>Seeds and search record ↓</span></a><a href="/archive/spring-hunt.json">Expanded spring certificates <span>JSON ↓</span></a><a href="/archive/spring-hunt-verification.json">Independent Python verification <span>JSON ↓</span></a><a href="/archive/research-notes.md">Original research notes <span>Markdown ↓</span></a><a href="/archive/cycle-certificate.json">Exact-cycle certificates <span>JSON ↓</span></a><a href="/archive/deposit-sweep.json">All 65 memory settings <span>JSON ↓</span></a><a href="/archive/spring-results.json">6,000-tick spring tests <span>JSON ↓</span></a><a href="/archive/cathedral-results.json">Cathedral controls <span>JSON ↓</span></a><a href="/archive/experiment-results.json">Estuary controls <span>JSON ↓</span></a><a href="/archive/search.json">First revised-rule search <span>144 settings ↓</span></a><a href="/archive/deeper.json">Second search <span>96 settings ↓</span></a><a href="/archive/seeds.json">Seed-search survivors <span>JSON ↓</span></a><a href="/archive/six-cell-spring.gif">Spring animation <span>GIF ↓</span></a><a href="https://github.com/junovhs/palimpsest/tree/main/reference">Python reference & search <span>GitHub ↗</span></a><a href="https://github.com/junovhs/palimpsest/blob/main/src/engine.ts">The TypeScript rule <span>GitHub ↗</span></a></aside>
</div>`;

export const notesStyles = `
.notes-heading{max-width:800px;margin:15px 0 52px}.notes-heading h1{font-size:clamp(2.4rem,5vw,4rem);font-weight:450;letter-spacing:-.045em;line-height:1.1;margin:0 0 18px}.notes-heading>p:not(.eyebrow){font-size:1.15rem;color:#b7c8d0}.note-meta{color:var(--muted);font-size:.8125rem}.notebook{display:grid;grid-template-columns:minmax(0,760px) 270px;gap:70px;align-items:start}.notebook article{min-width:0}.notebook article>section{padding:0 0 38px;margin-bottom:34px;border-bottom:1px solid var(--line)}.notebook h2{font-size:1.6rem;letter-spacing:-.025em;font-weight:450;line-height:1.3;margin:0 0 20px}.notebook p,.notebook li{font-size:1rem;line-height:1.8;color:#b9cbd4}.notebook strong{color:#e7eff2;font-weight:550}.notebook li{padding-left:5px;margin:12px 0}.notebook a{color:var(--a);font-size:.9375rem}.notebook code{font-family:ui-monospace,monospace;font-size:.875em;color:#d3e6ec}.notebook pre{overflow-x:auto;padding:24px;background:#0e1922;border:1px solid var(--line);line-height:1.75;margin:22px 0}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;margin:22px 0;font-size:.9375rem;text-align:left}th{font-weight:500;color:var(--muted)}td,th{padding:14px 12px;border-bottom:1px solid var(--line)}td:first-child,th:first-child{padding-left:0}.seed-figure{display:flex;gap:28px;align-items:center;padding:20px 0}.seed-grid{display:grid;grid-template-columns:repeat(2,46px);gap:5px}.seed-grid span{display:grid;place-items:center;width:46px;height:46px;background:#17232d;border:1px solid #3c515e;font-family:ui-monospace,monospace;font-size:1rem}.seed-grid .seed-a{background:#17483e;color:var(--a);border-color:#438a77}.seed-figure p{font-size:.875rem;line-height:1.9}.inline-action{display:inline-block;padding:8px 0}.cycle-line{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:28px 0;padding:24px 0;border-block:1px solid var(--line)}.cycle-line span{font-size:.8125rem;color:var(--muted)}.cycle-line strong{display:block;font-family:ui-monospace,monospace;font-size:1.8rem;color:var(--a);font-weight:400;margin-bottom:8px}.archive{border-top:1px solid var(--line);padding-top:20px}.archive h2{font-size:1.15rem}.archive>a{display:block;padding:16px 0;border-bottom:1px solid var(--line);color:#d2e0e6;font-size:.875rem;text-decoration:none;line-height:1.5}.archive>a:hover{color:var(--a)}.archive>a>span{display:block;color:var(--muted);font-size:.75rem;margin-top:5px}.source-list{padding-left:18px}.source-list a{font-size:.875rem}@media(max-width:1000px){.notebook{grid-template-columns:minmax(0,1fr) 230px;gap:32px}}@media(max-width:760px){.notebook{grid-template-columns:1fr;gap:20px}.notes-heading{margin-bottom:36px}.archive{margin-bottom:20px}.notebook h2{font-size:1.45rem}.notebook pre{padding:16px}}`;
