import { MODULES, KINDS, definition, editPatch, initialPatch, makeNode, resolvePatch, type Patch, type PatchNode, type Kind } from './patch';
import { SYNTH_PRESETS, type SynthPreset } from './synth-presets';
export type PatchHost={get:()=>Patch|undefined;change:(patch:Patch,checkpoint?:boolean)=>void;time:()=>number;activity:()=>number;save:()=>void;load:(p:SynthPreset)=>void;preview:HTMLCanvasElement;thumbnail:(p:SynthPreset,c:HTMLCanvasElement)=>Promise<void>;pause:()=>void;running:()=>boolean;undo:()=>void;canUndo:()=>boolean};
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export class PatchEditor {
  private selected='';private wire:string|null=null;private zoom=.8;private initializedThumbs=false;
  constructor(private host:PatchHost){
    document.body.insertAdjacentHTML('beforeend',`
      <dialog id="preset-browser" aria-labelledby="preset-title"><header class="preset-header"><div><span class="eyebrow">THE VISUAL SYNTH / 20 STARTING POINTS</span><h2 id="preset-title">A different kind of beautiful.</h2><p>Choose a world. Open its blueprint. Make it your own.</p></div><button data-close="preset-browser" aria-label="Close presets">✕</button></header><div class="preset-filters"><input id="preset-search" aria-label="Search presets" type="search" placeholder="Search a feeling, material, or effect…"><select id="preset-family" aria-label="Preset family"><option>All families</option>${['Material','Atmosphere','Geometry','Particles','Print'].map(x=>`<option>${x}</option>`).join('')}</select></div><div id="preset-grid" class="preset-grid">${SYNTH_PRESETS.map(p=>`<button class="preset-card" data-preset="${p.id}"><canvas width="240" height="150" aria-hidden="true"></canvas><span><small>${p.family} / ${p.patch.nodes.length} modules</small><strong>${p.name}</strong><em>${p.description}</em></span></button>`).join('')}</div><p id="preset-empty" hidden>No matches. Try another word or family.</p></dialog>
      <dialog id="patch-editor" aria-labelledby="patch-title"><header class="patch-header"><div><span class="eyebrow">PALIMPSEST / VISUAL SYNTH</span><h2 id="patch-title">The blueprint<span>.</span></h2></div><div class="patch-header-actions"><button id="patch-play">Pause</button><button id="patch-undo">Undo</button><button id="patch-save">Save patch</button><button data-close="patch-editor" aria-label="Close blueprint">Done ↗</button></div></header>
      <div class="patch-toolbar"><label>Add a module<select id="module-kind">${['Source','Space','Tone','Light','Mix','Signal'].map(g=>`<optgroup label="${g}">${KINDS.filter(k=>definition(k).group===g).map(k=>`<option value="${k}">${definition(k).name}</option>`).join('')}</optgroup>`).join('')}</select></label><button id="module-add">＋ Add</button><span class="wire-key"><i></i> Image <i class="signal"></i> Signal</span><div class="patch-zoom"><button id="patch-zoom-out" aria-label="Zoom out of blueprint">−</button><button id="patch-fit">Fit</button><button id="patch-zoom-in" aria-label="Zoom into blueprint">＋</button></div></div>
      <div class="patch-workspace"><div id="graph-viewport" tabindex="0" aria-label="Blueprint canvas. Scroll to pan; drag module headers to arrange. Connect an output port to an input port."><div id="graph-extent"><div id="graph-plane"><svg id="patch-wires" aria-hidden="true"></svg><div id="patch-nodes"></div></div></div></div><aside class="node-inspector"><div class="patch-preview-wrap"><canvas id="patch-preview" width="400" height="225" aria-label="Live patch output"></canvas><span>LIVE OUTPUT <b id="patch-module-count"></b></span></div><div id="node-settings"></div></aside></div><footer class="patch-footer"><span id="patch-status" role="status">Click an output dot, then an input dot to connect. Violet signals modulate parameters.</span><button id="patch-cancel-wire" hidden>Cancel wire</button></footer></dialog>`);
    for(const b of document.querySelectorAll<HTMLButtonElement>('[data-close]'))b.onclick=()=>$(b.dataset.close!) instanceof HTMLDialogElement&&$(b.dataset.close!) && ($<HTMLDialogElement>(b.dataset.close!).close());
    $('preset-search').oninput=$('preset-family').onchange=()=>this.filterPresets();
    for(const b of document.querySelectorAll<HTMLButtonElement>('[data-preset]'))b.onclick=()=>{this.host.load(SYNTH_PRESETS.find(p=>p.id===b.dataset.preset)!);$<HTMLDialogElement>('preset-browser').close();};
    $('patch-save').onclick=()=>{$<HTMLDialogElement>('patch-editor').close();this.host.save();};
    $('patch-play').onclick=()=>{this.host.pause();this.updatePreview();};
    $('patch-undo').onclick=()=>{this.host.undo();this.sync();};
    $('module-add').onclick=()=>this.add($<HTMLSelectElement>('module-kind').value as Kind);
    $('patch-fit').onclick=()=>this.fit();
    $('patch-zoom-in').onclick=()=>this.setZoom(this.zoom*1.2);
    $('patch-zoom-out').onclick=()=>this.setZoom(this.zoom/1.2);
    $('patch-cancel-wire').onclick=()=>this.cancelWire();
    $('graph-viewport').onkeydown=e=>{if(e.key==='Escape'&&this.wire){e.preventDefault();this.cancelWire();}if((e.key==='Delete'||e.key==='Backspace')&&e.target===$('graph-viewport')){e.preventDefault();this.remove();}};
    $<HTMLDialogElement>('patch-editor').addEventListener('cancel',e=>{if(this.wire){e.preventDefault();this.cancelWire();}});
  }
  open(){if(!this.host.get())this.host.change(initialPatch());this.selected=this.host.get()!.output;this.wire=null;this.render();$<HTMLDialogElement>('patch-editor').showModal();requestAnimationFrame(()=>{this.setZoom(innerWidth<760?.65:.85);$('graph-viewport').scrollLeft=0;$('graph-viewport').scrollTop=0;this.updatePreview();});}
  async browse(){
    $<HTMLDialogElement>('preset-browser').showModal();
    if(this.initializedThumbs)return;this.initializedThumbs=true;
    for(const p of SYNTH_PRESETS){const c=document.querySelector<HTMLCanvasElement>(`[data-preset="${p.id}"] canvas`)!;try{await this.host.thumbnail(p,c);}catch{c.classList.add('thumbnail-unavailable');}await new Promise<void>(r=>requestAnimationFrame(()=>r()));}
  }
  private filterPresets(){const q=$<HTMLInputElement>('preset-search').value.toLowerCase(),family=$<HTMLSelectElement>('preset-family').value;let count=0;for(const p of SYNTH_PRESETS){const hidden=!(p.name+' '+p.description+' '+p.family).toLowerCase().includes(q)||(family!=='All families'&&family!==p.family);document.querySelector<HTMLElement>(`[data-preset="${p.id}"]`)!.hidden=hidden;if(!hidden)count++;}$('preset-empty').hidden=count>0;}
  private commit(edit:(p:Patch)=>void,checkpoint=true,rebuild=true){try{const next=editPatch(this.host.get()!,edit);this.host.change(next,checkpoint);if(rebuild)this.render();$('patch-status').textContent='Patch connected. Changes are live.';return true;}catch(e){$('patch-status').textContent=e instanceof Error?e.message:'Could not connect those modules.';return false;}}
  sync(){if($<HTMLDialogElement>('patch-editor').open){if(this.host.get())this.render();else $<HTMLDialogElement>('patch-editor').close();}}
  updatePreview(){if(!$<HTMLDialogElement>('patch-editor').open)return;const c=$<HTMLCanvasElement>('patch-preview');const ctx=c.getContext('2d')!,source=this.host.preview,scale=Math.min(c.width/source.width,c.height/source.height);ctx.fillStyle='#0c171b';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(source,(c.width-source.width*scale)/2,(c.height-source.height*scale)/2,source.width*scale,source.height*scale);$('patch-play').textContent=this.host.running()?'Pause':'Run';$<HTMLButtonElement>('patch-undo').disabled=!this.host.canUndo();
    const patch=this.host.get();if(patch){const signals=resolvePatch(patch,this.host.time(),this.host.activity()).signals;for(const [id,v] of signals){const out=document.querySelector<HTMLElement>(`[data-signal-value="${id}"]`);if(out)out.textContent=v.toFixed(2);}}
  }
  private add(kind:Kind){const p=this.host.get()!;if(p.nodes.length>=24){$('patch-status').textContent='This patch has 24 modules. Remove one before adding another.';return;}const selected=p.nodes.find(n=>n.id===this.selected),n=makeNode(kind,undefined,Math.min(11000,(selected?.x||0)+270),selected?.y||80);if(definition(kind).group==='Signal'){n.y+=240;}else if(n.inputs.length&&selected&&definition(selected.kind).group!=='Signal')n.inputs[0]=selected.id;this.selected=n.id;this.commit(p=>{p.nodes.push(n);if(definition(kind).group!=='Signal')p.output=n.id;});this.reveal(n);}
  private cancelWire(){this.wire=null;$('patch-cancel-wire').hidden=true;$('patch-status').textContent='Click an output dot, then an input dot to connect.';document.querySelectorAll('.is-wiring').forEach(n=>n.classList.remove('is-wiring'));}
  private output(id:string){this.wire=id;this.renderNodes();$('patch-cancel-wire').hidden=false;$('patch-status').textContent=definition(this.host.get()!.nodes.find(n=>n.id===id)!.kind).group==='Signal'?'Choose a violet parameter dot or a signal input.':'Choose an image input dot on another module.';}
  private connect(target:string,port:number|string){if(!this.wire){$('patch-status').textContent='First choose an output dot on a source module.';return;}const source=this.wire;const connected=this.commit(p=>{const n=p.nodes.find(n=>n.id===target)!;if(typeof port==='number')n.inputs[port]=source;else n.mods[port]={source,depth:n.mods[port]?.depth??.2};});if(connected)this.cancelWire();this.render();}
  private render(){const patch=this.host.get()!;if(!patch.nodes.some(n=>n.id===this.selected))this.selected=patch.output;$('patch-module-count').textContent=`${patch.nodes.length} / 24`;this.renderNodes();this.renderSettings();this.sizePlane();this.drawWires();}
  private renderNodes(){
    const patch=this.host.get()!;
    $('patch-nodes').innerHTML=patch.nodes.map(n=>{const d=definition(n.kind),signal=d.group==='Signal';return `<article class="patch-node ${signal?'signal-node':''} ${n.id===this.selected?'selected':''} ${n.bypass?'bypassed':''} ${n.id===this.wire?'is-wiring':''}" data-node="${n.id}" style="left:${n.x}px;top:${n.y}px"><header tabindex="0" role="button" aria-label="Select ${escape(d.name)}" data-node-select="${n.id}"><span>${d.group}</span><strong>${d.name}</strong><small>${n.id===patch.output?'OUTPUT':n.bypass?'BYPASSED':signal?'MODULATOR':'MODULE'}</small></header><div class="node-ports">${n.inputs.map((id,i)=>`<button class="port input-port ${signal?'signal':''}" data-input="${n.id}" data-port="${i}" aria-label="${d.name} input ${i+1}"><i></i>${signal?String.fromCharCode(65+i):i===0?'Image':n.kind==='warp'?'Map':n.kind==='mask'?'Mask':'Image B'}<small>${id?'●':'○'}</small></button>`).join('')}<button class="port output-port ${signal?'signal':''}" data-output="${n.id}" aria-label="${d.name} ${signal?'signal':'image'} output">${signal?'Signal':'Image'}<i></i></button></div><div class="node-summary">${signal?`<span data-signal-value="${n.id}">0.00</span> · modulation signal`:Object.entries(d.params).slice(0,2).map(([key,param])=>`<span>${param.name} <b>${param.options?param.options[n.params[key]]:Number(n.params[key].toFixed(2))}</b></span>`).join('')||'<span>Original cellular material</span>'}</div>${Object.entries(d.params).filter(([,param])=>!param.options).map(([key,param])=>`<button class="mod-port ${n.mods[key]?'connected':''}" data-mod="${n.id}" data-param="${key}" aria-label="Modulate ${d.name} ${param.name}"><i></i>${param.name}${n.mods[key]?' ↗':''}</button>`).join('')}</article>`;}).join('');
    for(const header of document.querySelectorAll<HTMLElement>('[data-node-select]')){
      header.onclick=()=>{this.selected=header.dataset.nodeSelect!;this.render();};header.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();this.selected=header.dataset.nodeSelect!;this.render();}};
      header.onpointerdown=e=>{if(e.button!==0)return;const n=patch.nodes.find(n=>n.id===header.dataset.nodeSelect)!,node=header.parentElement!;const sx=e.clientX,sy=e.clientY,ox=n.x,oy=n.y;let x=ox,y=oy,moved=false;header.setPointerCapture(e.pointerId);
        header.onpointermove=event=>{x=Math.max(0,Math.min(11000,ox+(event.clientX-sx)/this.zoom));y=Math.max(0,Math.min(11000,oy+(event.clientY-sy)/this.zoom));moved=Math.abs(x-ox)+Math.abs(y-oy)>3;node.style.left=`${x}px`;node.style.top=`${y}px`;this.drawWires();};
        const end=()=>{header.onpointermove=null;header.onpointerup=null;header.onpointercancel=null;if(moved){this.selected=n.id;this.commit(p=>{const target=p.nodes.find(a=>a.id===n.id)!;target.x=x;target.y=y;});}};header.onpointerup=end;header.onpointercancel=end;
      };
    }
    for(const b of document.querySelectorAll<HTMLButtonElement>('[data-output]'))b.onclick=()=>this.output(b.dataset.output!);
    for(const b of document.querySelectorAll<HTMLButtonElement>('[data-input]'))b.onclick=()=>this.connect(b.dataset.input!,Number(b.dataset.port));
    for(const b of document.querySelectorAll<HTMLButtonElement>('[data-mod]'))b.onclick=()=>{if(this.wire)this.connect(b.dataset.mod!,b.dataset.param!);else{this.selected=b.dataset.mod!;this.render();$('patch-status').textContent='Connect an LFO or activity output here, or use the modulation dropdown.';}};
  }
  private renderSettings(){
    const patch=this.host.get()!,n=patch.nodes.find(n=>n.id===this.selected)!,d=definition(n.kind),signals=patch.nodes.filter(p=>definition(p.kind).group==='Signal'),images=patch.nodes.filter(p=>definition(p.kind).group!=='Signal');
    const options=(list:PatchNode[],value:string|null)=>`<option value="">Not connected</option>${list.filter(p=>p.id!==n.id).map(p=>`<option value="${p.id}" ${value===p.id?'selected':''}>${definition(p.kind).name} · ${patch.nodes.indexOf(p)+1}</option>`).join('')}`;
    $('node-settings').innerHTML=`<span class="eyebrow">${d.group.toUpperCase()} MODULE</span><h3>${d.name}</h3><p>${d.description}</p><div class="node-actions"><button id="node-bypass" aria-pressed="${n.bypass}">${n.bypass?'Enable':'Bypass'}</button><button id="node-duplicate">Duplicate</button><button id="node-remove" ${patch.nodes.length===1?'disabled':''}>Remove</button></div>${d.group!=='Signal'?`<button class="node-output-button" id="node-output" ${patch.output===n.id?'disabled':''}>${patch.output===n.id?'✓ Final output':'Use as final output'}</button>`:''}${n.inputs.map((value,i)=>`<label>Input ${i+1}<select data-setting-input="${i}">${options(d.group==='Signal'?signals:images,value)}</select></label>`).join('')}${Object.entries(d.params).map(([key,param])=>`<div class="node-parameter"><label>${param.name}<output id="patch-value-${key}">${param.options?'':Number(n.params[key].toFixed(3))}</output>${param.options?`<select data-knob="${key}">${param.options.map((s,i)=>`<option value="${i}" ${i===n.params[key]?'selected':''}>${s}</option>`).join('')}</select>`:`<input data-knob="${key}" type="range" min="${param.min}" max="${param.max}" step="${param.step||.01}" value="${n.params[key]}">`}</label>${!param.options?`<details ${n.mods[key]?'open':''}><summary>Modulate ${param.name}</summary><label>Signal<select data-setting-mod="${key}">${options(signals,n.mods[key]?.source||null)}</select></label><label>Depth <output id="mod-value-${key}">${n.mods[key]?.depth??.2}</output><input data-depth="${key}" type="range" min="-1" max="1" step=".01" value="${n.mods[key]?.depth??.2}" ${n.mods[key]?'':'disabled'}></label></details>`:''}</div>`).join('')}`;
    $('node-bypass').onclick=()=>this.commit(p=>{p.nodes.find(a=>a.id===n.id)!.bypass=!n.bypass;});
    $('node-duplicate').onclick=()=>{if(patch.nodes.length>=24){$('patch-status').textContent='24-module limit reached.';return;}const copy=structuredClone(n);copy.id=crypto.randomUUID();copy.x=Math.min(11000,copy.x+45);copy.y=Math.min(11000,copy.y+220);this.selected=copy.id;this.commit(p=>p.nodes.push(copy));};
    $('node-remove').onclick=()=>this.remove();
    if(d.group!=='Signal')$('node-output').onclick=()=>this.commit(p=>{p.output=n.id;});
    for(const select of document.querySelectorAll<HTMLSelectElement>('[data-setting-input]'))select.onchange=()=>this.commit(p=>{p.nodes.find(a=>a.id===n.id)!.inputs[Number(select.dataset.settingInput)]=select.value||null;});
    for(const select of document.querySelectorAll<HTMLSelectElement>('[data-setting-mod]'))select.onchange=()=>this.commit(p=>{const target=p.nodes.find(a=>a.id===n.id)!;const key=select.dataset.settingMod!;if(select.value)target.mods[key]={source:select.value,depth:.2};else delete target.mods[key];});
    for(const knob of document.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-knob],[data-depth]')){
      let editing=false;
      knob.oninput=()=>{const key=knob.dataset.knob||knob.dataset.depth!,value=Number(knob.value);this.commit(p=>{const target=p.nodes.find(a=>a.id===n.id)!;if(knob.dataset.depth)target.mods[key].depth=value;else target.params[key]=value;},!editing,false);editing=true;const output=$(knob.dataset.depth?`mod-value-${key}`:`patch-value-${key}`);if(output)output.textContent=String(value);this.renderNodes();this.drawWires();};
      knob.onchange=()=>{editing=false;};knob.onblur=()=>{editing=false;};
    }
  }
  private remove(){const p=this.host.get()!,n=p.nodes.find(n=>n.id===this.selected)!;if(p.nodes.length===1)return;this.commit(p=>{const fallback=n.inputs[0]||p.nodes.find(a=>a.id!==n.id&&definition(a.kind).group!=='Signal')?.id;for(const a of p.nodes){a.inputs=a.inputs.map(id=>id===n.id?n.inputs[0]||null:id);for(const [k,m] of Object.entries(a.mods))if(m.source===n.id)delete a.mods[k];}p.nodes=p.nodes.filter(a=>a.id!==n.id);if(p.output===n.id)p.output=fallback||'';});}
  private sizePlane(){const nodes=this.host.get()!.nodes,w=Math.max(900,...nodes.map(n=>n.x+320)),h=Math.max(600,...nodes.map(n=>n.y+420));$('graph-plane').style.width=`${w}px`;$('graph-plane').style.height=`${h}px`;$('graph-extent').style.width=`${w*this.zoom}px`;$('graph-extent').style.height=`${h*this.zoom}px`;$('graph-plane').style.transform=`scale(${this.zoom})`;}
  private setZoom(z:number){this.zoom=Math.max(.25,Math.min(1.5,z));this.sizePlane();this.drawWires();}
  private fit(){const viewport=$('graph-viewport'),p=this.host.get()!;const width=Math.max(...p.nodes.map(n=>n.x+280)),height=Math.max(...p.nodes.map(n=>n.y+400));this.setZoom(Math.min(viewport.clientWidth/width,viewport.clientHeight/height,.9));viewport.scrollLeft=viewport.scrollTop=0;}
  private reveal(n:PatchNode){const v=$('graph-viewport');v.scrollLeft=Math.max(0,n.x*this.zoom-v.clientWidth/2);v.scrollTop=Math.max(0,n.y*this.zoom-v.clientHeight/2);}
  private drawWires(){const plane=$('graph-plane').getBoundingClientRect();const point=(selector:string,right:boolean)=>{const e=document.querySelector<HTMLElement>(selector);if(!e)return null;const r=e.getBoundingClientRect();return {x:((right?r.right:r.left)-plane.left)/this.zoom,y:(r.top+r.height/2-plane.top)/this.zoom};};const paths:string[]=[];const line=(source:string,target:string,port:number|string,signal:boolean)=>{const a=point(`[data-output="${source}"] i`,true),b=point(typeof port==='number'?`[data-input="${target}"][data-port="${port}"] i`:`[data-mod="${target}"][data-param="${port}"] i`,false);if(a&&b){const bend=Math.max(60,Math.abs(b.x-a.x)*.5);paths.push(`<path class="${signal?'signal-wire':''}" d="M${a.x},${a.y} C${a.x+bend},${a.y} ${b.x-bend},${b.y} ${b.x},${b.y}"/>`);}};for(const n of this.host.get()!.nodes){n.inputs.forEach((id,i)=>{if(id)line(id,n.id,i,definition(n.kind).group==='Signal');});for(const [key,m] of Object.entries(n.mods))line(m.source,n.id,key,true);}$('patch-wires').innerHTML=paths.join('');}
}
