// Generated by scripts/springs.ts; see archived certificates and independent Python verification.
export const NEW_SPRINGS = {
  "spring5": {
    "seed": [
      [
        -1,
        0,
        0,
        3
      ],
      [
        0,
        0,
        0,
        4
      ],
      [
        1,
        0,
        1,
        0
      ],
      [
        0,
        1,
        0,
        4
      ],
      [
        1,
        1,
        1,
        0
      ]
    ],
    "certificates": [
      {
        "grid": 48,
        "transient": 52,
        "period": 26,
        "repeat": 78,
        "sha256": "4101ed29df1aea328476643f3d9e4f42da9ed09437ea49c76d767634f52a89e2",
        "active": 360,
        "exactArraysVerified": true
      },
      {
        "grid": 96,
        "transient": 76,
        "period": 26,
        "repeat": 102,
        "sha256": "fc7d971e0d40e357f589d905a07c4ec48c73cce59f1a655b96117ab9c7982c73",
        "active": 1440,
        "exactArraysVerified": true
      },
      {
        "grid": 192,
        "transient": 124,
        "period": 26,
        "repeat": 150,
        "sha256": "28afc5cd2597f83888c48103a3ebc35907e3b835447e63440cc04f63c51d54a8",
        "active": 5708,
        "exactArraysVerified": true
      }
    ]
  },
  "spring8": {
    "seed": [
      [
        -1,
        -1,
        1,
        0
      ],
      [
        0,
        -1,
        0,
        2
      ],
      [
        1,
        -1,
        1,
        0
      ],
      [
        -1,
        0,
        0,
        4
      ],
      [
        1,
        0,
        1,
        0
      ],
      [
        -1,
        1,
        0,
        3
      ],
      [
        0,
        1,
        0,
        2
      ],
      [
        1,
        1,
        0,
        3
      ]
    ],
    "certificates": [
      {
        "grid": 48,
        "transient": 37,
        "period": 26,
        "repeat": 63,
        "sha256": "46feec64a312ead349918a6732359edf315d97f609b47bf8598c9a0b37352bb0",
        "active": 295,
        "exactArraysVerified": true
      },
      {
        "grid": 96,
        "transient": 61,
        "period": 26,
        "repeat": 87,
        "sha256": "9c9c97de6a1a19a1eed185b07b58b49eb6184be043d1d54eca421283eaeb0886",
        "active": 1286,
        "exactArraysVerified": true
      },
      {
        "grid": 192,
        "transient": 109,
        "period": 26,
        "repeat": 135,
        "sha256": "711a31d1bc5f56a5454d7a653e10232ac803eff0f0353da532385065b12579b0",
        "active": 5404,
        "exactArraysVerified": true
      }
    ]
  },
  "spring6b": {
    "seed": [
      [
        1,
        -1,
        1,
        0
      ],
      [
        0,
        0,
        0,
        4
      ],
      [
        1,
        0,
        0,
        2
      ],
      [
        0,
        1,
        0,
        3
      ],
      [
        1,
        1,
        1,
        0
      ],
      [
        0,
        -1,
        0,
        4
      ]
    ],
    "certificates": [
      {
        "grid": 48,
        "transient": 39,
        "period": 26,
        "repeat": 65,
        "sha256": "65e51440775000f7797e859762e096860539090c24114a35e8c8077567afb9cb",
        "active": 330,
        "exactArraysVerified": true
      },
      {
        "grid": 96,
        "transient": 63,
        "period": 26,
        "repeat": 89,
        "sha256": "32532be43287fc935c41542f90b6a50493b812120515566d57a4906c5e5ff177",
        "active": 1377,
        "exactArraysVerified": true
      },
      {
        "grid": 192,
        "transient": 111,
        "period": 26,
        "repeat": 137,
        "sha256": "6388def2c501ccae0d4dd5e6b148beac672b17dc4b42303c6e47208f80f8fe4f",
        "active": 5578,
        "exactArraysVerified": true
      }
    ]
  }
} as const;
