import { makeNode, validatePatch, type Kind, type Patch, type PatchNode } from './patch';
import type { PaletteName } from './palettes';
import type { ArtSettings } from './organic';
export type SynthPreset={id:string;name:string;family:'Material'|'Atmosphere'|'Geometry'|'Particles'|'Print';description:string;seed:number;palette:PaletteName;surface:ArtSettings['surface'];softness:number;relief:number;afterglow:number;speed:number;patch:Patch};
class Builder {
  nodes:PatchNode[]=[];last='';
  add(kind:Kind,params:Record<string,number>={},inputs?:Array<string|null>){const n=makeNode(kind,`${kind}-${this.nodes.length+1}`);Object.assign(n.params,params);if(inputs)n.inputs=inputs;else if(n.inputs.length&&this.last)n.inputs[0]=this.last;this.nodes.push(n);if(!['lfo','activity','math'].includes(kind))this.last=n.id;return n.id;}
  mod(target:string,param:string,source:string,depth:number){this.nodes.find(n=>n.id===target)!.mods[param]={source,depth};}
  patch():Patch {
    const depth=new Map<string,number>(),rows=new Map<number,number>();
    for(const n of this.nodes){const d=Math.max(0,...n.inputs.filter(Boolean).map(id=>(depth.get(id!)||0)+1));depth.set(n.id,d);const row=rows.get(d)||0;rows.set(d,row+1);n.x=70+d*270;n.y=70+row*220;if(['lfo','activity','math'].includes(n.kind)){n.y+=360;}}
    const p:Patch={version:1,nodes:this.nodes,output:this.last};validatePatch(p);return p;
  }
}
function preset(id:string,name:string,family:SynthPreset['family'],description:string,build:(b:Builder)=>void,options:Partial<Omit<SynthPreset,'patch'>>={}):SynthPreset {
  const b=new Builder();build(b);return {id,name,family,description,seed:21,palette:'ember',surface:'molten',softness:65,relief:55,afterglow:35,speed:8,...options,patch:b.patch()};
}
export const SYNTH_PRESETS:SynthPreset[]=[
  preset('lava','Slow Lava','Material','Living gold, refracted at the edges. Your original material with a breathing lens.',b=>{b.add('life');const w=b.add('warp',{amount:.035,scale:3,speed:.06});b.add('bloom',{amount:.15,radius:9});const l=b.add('lfo',{rate:.035});b.mod(w,'amount',l,.035);}),
  preset('tide','Tidal Glass','Material','Cool cellular glass with moving refraction and a soft specular finish.',b=>{b.add('life');b.add('prism',{distance:.008,angle:35});b.add('bloom',{amount:.28,radius:12});},{palette:'signal',seed:37,softness:83,relief:75,afterglow:65,speed:6}),
  preset('bloom','Night Bloom','Atmosphere','Diffuse orchid clouds drifting through a symmetrical night garden.',b=>{b.add('noise',{scale:4,detail:.55,drift:.14});b.add('mirror',{axis:0});b.add('palette',{theme:2,contrast:1.9});b.add('bloom',{amount:.35,radius:28});},{palette:'aurora',surface:'mist',seed:9,softness:90,relief:25,afterglow:75,speed:5}),
  preset('silk','Silver Silk','Material','Pearlescent folded ribbons, sculpted by noise and lit from a moving angle.',b=>{const n=b.add('noise',{scale:3,detail:.35});const w=b.add('waves',{frequency:6,angle:35,speed:.12},[]);b.add('warp',{amount:.16},[w,n]);b.add('palette',{theme:3,contrast:1.3});const e=b.add('emboss',{depth:3.2,metal:.6});const l=b.add('lfo',{rate:.025});b.mod(e,'angle',l,.18);},{palette:'mono',surface:'satin',seed:61,softness:52,relief:80,afterglow:55,speed:7}),
  preset('aurora','Aurora Veil','Atmosphere','Long curtains of green light, bent by slowly drifting cloud fields.',b=>{const n=b.add('noise',{scale:3,drift:.08});const w=b.add('waves',{frequency:3,angle:10,speed:.15},[]);b.add('warp',{amount:.3},[w,n]);b.add('blur',{radius:18});b.add('palette',{theme:1,contrast:1.3,shift:-.16});b.add('bloom',{amount:.22,radius:30});}),
  preset('nebula','Velvet Nebula','Atmosphere','Deep, billowing color with a second star field screened into the clouds.',b=>{b.add('noise',{scale:3,detail:.7});const c=b.add('palette',{theme:2,contrast:2});b.add('stars',{density:40,size:.08});const stars=b.add('bloom',{amount:1,radius:8});b.add('blend',{mode:1,amount:.8},[c,stars]);},{seed:44}),
  preset('sunwash','Sunwash','Atmosphere','A soft solar wash: large merging bodies, diffused into warm gradients.',b=>{b.add('orbits',{count:4,size:.26,speed:.11});b.add('blur',{radius:24});b.add('palette',{theme:7,contrast:1.1});b.add('grain',{amount:.026});}),
  preset('ink','Ink in Water','Material','Islands of cobalt ink, cut from noise and pulled through a moving field.',b=>{b.add('noise',{scale:5,detail:.7});const cut=b.add('threshold',{level:.5,softness:.09});b.add('warp',{amount:.16,scale:5,speed:.08});b.add('palette',{theme:4});const l=b.add('lfo',{rate:.025});b.mod(cut,'level',l,.13);},{seed:13}),
  preset('mercury','Mercury Garden','Material','Merging silver bodies with bright metallic ridges and a wandering light.',b=>{b.add('orbits',{count:7,size:.15,speed:.16});b.add('palette',{theme:9});const e=b.add('emboss',{depth:5,metal:.95});const l=b.add('lfo',{rate:.03});b.mod(e,'angle',l,.4);}),
  preset('opal','Opal Cells','Material','Moving mineral cells with rose color and spectral edges.',b=>{b.add('cells',{scale:6,motion:.15,style:0});b.add('palette',{theme:6,contrast:1.1});b.add('emboss',{depth:2,metal:.65});const p=b.add('prism',{distance:.013,angle:20});const l=b.add('lfo',{rate:.045});b.mod(p,'distance',l,.1);}),
  preset('topography','Topography','Print','Fine contour lines over moss-colored terrain, finished with restrained grain.',b=>{b.add('noise',{scale:3,detail:.15,drift:.06});b.add('contours',{count:12,width:.14});b.add('palette',{theme:5});b.add('grain',{amount:.055});}),
  preset('risograph','Riso Drift','Print','Graphic coral islands with a tactile, print-like grain.',b=>{b.add('noise',{scale:7,detail:.25,drift:.07});b.add('threshold',{level:.48,softness:.007});b.add('palette',{theme:6});b.add('grain',{amount:.18,scale:1.5});}),
  preset('moire','Moiré Study','Geometry','Two independent wave branches interfere; one slowly rotates against the other.',b=>{const a=b.add('waves',{frequency:27,speed:.1});b.add('waves',{frequency:28,angle:4,speed:-.13},[]);const t=b.add('transform',{angle:3});b.add('blend',{mode:4,amount:1},[a,t]);b.add('palette',{theme:9,contrast:1.6});const l=b.add('lfo',{rate:.016});b.mod(t,'angle',l,.02);}),
  preset('rosewindow','Rose Window','Geometry','Radial stained-glass geometry grown from cellular edges.',b=>{b.add('cells',{scale:5,style:1,motion:.09});b.add('palette',{theme:11,contrast:1.5});const k=b.add('kaleido',{sides:8,zoom:.9});b.add('bloom',{amount:.35,radius:8});const l=b.add('lfo',{rate:.014});b.mod(k,'angle',l,.15);}),
  preset('portal','Electric Portal','Geometry','A luminous blue tunnel, assembled from polar waves and refracted light.',b=>{b.add('waves',{frequency:10,angle:90,speed:.5});b.add('threshold',{level:.82,softness:.08});b.add('polar',{twist:.8,scale:1.6});b.add('palette',{theme:4,contrast:1.1});b.add('prism',{distance:.01});b.add('bloom',{amount:.4,radius:12});}),
  preset('interference','Signal Interference','Geometry','An analog-feeling interference pattern that slips through color and distortion.',b=>{b.add('waves',{frequency:7,shape:2,speed:.3});const warp=b.add('warp',{amount:.09,scale:6});b.add('palette',{theme:11});b.add('prism',{distance:.02,angle:90});const l=b.add('lfo',{rate:.09});const a=b.add('activity',{gain:2});const m=b.add('math',{operation:0,gain:.4},[l,a]);b.mod(warp,'amount',m,.18);}),
  preset('stardust','Stardust','Particles','A field of softly glowing icy particles; density follows the cellular world.',b=>{const s=b.add('stars',{density:35,size:.13,speed:.12});b.add('palette',{theme:8,contrast:1.8,shift:-.13});b.add('bloom',{amount:1.1,radius:10});const a=b.add('activity',{gain:2});b.mod(s,'density',a,.3);}),
  preset('fireflies','Firefly Trails','Particles','Warm points leave soft, slowly turning echoes behind them.',b=>{b.add('stars',{density:18,size:.18,speed:.55});b.add('palette',{theme:0,contrast:1.9,shift:-.12});b.add('echo',{decay:.9,zoom:1.004,angle:.3});b.add('bloom',{amount:1.2,radius:12});}),
  preset('paper','Paper Cut','Print','Layered graphic bands, folded into a restrained sculptural composition.',b=>{b.add('noise',{scale:3,detail:.3,drift:.05});b.add('contours',{count:5,width:.8});b.add('palette',{theme:3});b.add('emboss',{depth:2.5,metal:.05});b.add('grain',{amount:.04});}),
  preset('afterimage','Chromatic Afterimage','Geometry','Mirrored interference, colored and fed through a rotating echo.',b=>{b.add('waves',{frequency:5,shape:2,speed:.65});b.add('mirror',{axis:2});b.add('palette',{theme:11});b.add('echo',{decay:.86,zoom:1.013,angle:1.2});const h=b.add('hue',{saturation:1.3});const l=b.add('lfo',{rate:.024});b.mod(h,'angle',l,.35);}),
];
