// Generated by scripts/travelers.ts; full-state translation verified over eight cycles.
export const TRAVELERS = {
  "skater": {
    "preset": "loom",
    "trial": 26,
    "from": 4,
    "to": 8,
    "dx": 1,
    "dy": -1,
    "seed": [
      [
        -1,
        -2,
        -1,
        0
      ],
      [
        0,
        -2,
        0,
        1
      ],
      [
        -2,
        -1,
        0,
        1
      ],
      [
        0,
        -1,
        0,
        1
      ],
      [
        2,
        -1,
        -1,
        0
      ],
      [
        0,
        0,
        -1,
        0
      ],
      [
        1,
        0,
        -1,
        0
      ],
      [
        2,
        0,
        0,
        1
      ],
      [
        -1,
        1,
        0,
        1
      ],
      [
        0,
        1,
        0,
        1
      ],
      [
        -1,
        2,
        0,
        1
      ],
      [
        0,
        2,
        0,
        1
      ],
      [
        1,
        2,
        0,
        1
      ],
      [
        2,
        2,
        0,
        1
      ]
    ],
    "period": 4,
    "grid": 128,
    "verifiedCycles": 8,
    "occupied": 6
  },
  "dart": {
    "preset": "comets",
    "trial": 0,
    "from": 4,
    "to": 8,
    "dx": 4,
    "dy": 0,
    "seed": [
      [
        -1,
        -2,
        0,
        1
      ],
      [
        0,
        -2,
        -1,
        0
      ],
      [
        1,
        -2,
        1,
        0
      ],
      [
        -2,
        -1,
        -1,
        0
      ],
      [
        -2,
        0,
        0,
        1
      ],
      [
        1,
        0,
        0,
        1
      ],
      [
        -2,
        1,
        -1,
        0
      ],
      [
        -1,
        1,
        0,
        1
      ],
      [
        0,
        1,
        0,
        1
      ],
      [
        1,
        1,
        -1,
        0
      ],
      [
        0,
        2,
        0,
        1
      ],
      [
        2,
        2,
        1,
        0
      ]
    ],
    "period": 4,
    "grid": 128,
    "verifiedCycles": 8,
    "occupied": 4
  }
} as const;
